# Generated by Django 5.1.7 on 2025-05-13 16:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_automated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField()),
                ('inspector', models.CharField(blank=True, max_length=100, null=True)),
                ('pci', models.IntegerField(help_text='0-100 scale where 100 is perfect condition', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pavement Condition Index')),
                ('rutting', models.FloatField(blank=True, help_text='Average rutting depth in mm', null=True)),
                ('cracking_percentage', models.FloatField(blank=True, help_text='Percentage of surface with cracking', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('roughness_iri', models.FloatField(blank=True, help_text='International Roughness Index (m/km)', null=True)),
                ('image_urls', models.JSONField(blank=True, null=True)),
                ('raw_data_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assessment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.assessmentmethod')),
                ('road_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.roadsection')),
            ],
            options={
                'ordering': ['-assessment_date'],
            },
        ),
    ]
