# Generated by Django 5.1.7 on 2025-05-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('road_id', models.CharField(max_length=50, unique=True)),
                ('length', models.FloatField(help_text='Length in meters')),
                ('width', models.FloatField(help_text='Width in meters')),
                ('surface_type', models.CharField(max_length=50)),
                ('construction_date', models.DateField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('geometry_data', models.TextField(blank=True, help_text='Geometry data in GeoJSON or WKT format', null=True)),
            ],
        ),
    ]
